name: cresce_vendas_app_v1
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.2.1
  flutter_mobx: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.0.4
  intl: ^0.18.1
  path_provider: ^2.1.1
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  mobx_codegen: ^2.4.0
  hive_generator: ^2.0.1
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/fonts/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-SemiBold.ttf
          weight: 600
